apiVersion: batch/v1
kind: Job
metadata:
  name: alter-user-password
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:latest
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: my-postgresql-credentials
              key: password
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: my-postgresql-credentials
              key: username
        - name: PGDATABASE
          value: goals_database
        command: ["sh", "-c"]
        args: ["psql -h my-postgresql-rw -U postgres -c \"ALTER USER goal WITH PASSWORD 'completed';\""]
      restartPolicy: OnFailure
